### ISSUE TITLE
ImportError: No module named lib

### ISSUE THREAD

**Issue by megapearl** [Torf/XDM-French-Touch#4]
By all of your plugins I get this error:

Error during importing of Indexer.T411-fr_torf_t411-0_108.T411
Traceback:
Traceback (most recent call last):
  File "##xdm_path##/xdm/plugins/pluginManager.py", line 377, in look_for_subclass
    module = **import**(modulename)
  File "##xdm_path##/plugins/Indexer/T411-fr_torf_t411-0_108/T411.py", line 23, in 
    from lib import requests
ImportError: No module named lib

What could be wrong? do I miss some python modules?
I already tried installing the peewee and requests modules using easy_install but that didn't work out.

Hope you can help me out,

Regards.
Donald.

**Comment by Torf** [comment]
OmyGad, I didn't see this issue sorry !

It's a problem coming from the XDM 5.5 update, I've fix it.

Thanks you for the issue.

edit: fixed in the dev branch, i will merge to head in the next days.
